# Stage 1: Builder
FROM node-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

COPY . .

RUN npx prisma generate
RUN npm run build

# Stage 2: Runner --------------
FROM node-alpine AS runner

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci--only=production

RUN npx prisma generate

COPY --from=builder /app/dist ./dist

EXPOSE 5000

CMD [ "node", "dist/server.js" ]