# Stage 1: Builder
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN ls -la && cat package.json

RUN npm ci --verbose

COPY . .

RUN npx prisma generate
RUN npm run build

# Stage 2: Runner --------------
FROM node:24-alpine AS runner

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --omit=dev

RUN npx prisma generate

COPY --from=builder /app/dist ./dist

EXPOSE 5000

COPY start.sh ./
RUN chmod +x start.sh
CMD [ "./start.sh" ]